const translations = {
    uz: {
        nav: { services: "Xizmatlar", portfolio: "Portfolio", process: "Jarayon", location: "Manzil", contact: "Bog'lanish", order: "Zakaz Berish", pricingNav: "Narxlar", about: "Men haqimda", themeDark: "QORONG'I", themeLight: "YORUG'" },
        hero: { badge: "Grafik Dizayner — Vobkent, Buxoro", t1: "GRAFIK", t2: "DIZAYN", t3: "PORTFOLIO", sub: "Infografika, poster, brend identifikatsiya — har bir loyiha o'ziga xos vizual til bilan yaratiladi.", btn1: "Ishlarni Ko'rish", btn2: "Zakaz Berish", s1: "Loyiha", s2: "Yil Tajriba", s3: "Mamnun Mijoz" },
        services: { title: "Xizmatlar", sub: "Har qanday loyiha uchun professional yechimlar", items: [{ title: "Infografika", desc: "Ma'lumotlarni vizual, tushunish oson formatda taqdim etish" }, { title: "Poster Dizayn", desc: "Tadbirlar, mahsulot va kompaniyalar uchun diqqatni tortuvchi posterlar" }, { title: "Brend Identifikatsiya", desc: "Logotip, ranglar, shriftlar va korporativ uslub" }, { title: "Sotsial Media", desc: "Instagram, Telegram va boshqa platformalar uchun kontentlar" }, { title: "Prezentatsiya", desc: "Biznes va ta'lim uchun professional slaydlar" }, { title: "Menyu Dizayn", desc: "Restoranlar uchun chiroyli menyular" }] },
        portfolio: { title: "Portfolio", sub: "So'nggi ishlar", items: ["Infografika dizayn", "Poster dizayn", "Brend identifikatsiya", "Sotsial media kontent", "Prezentatsiya"], viewAll: "Barcha ishlarni ko'rish" },
        gallery: { title: "Dizayn Galereyasi", sub: "Barcha loyihalar to'plami", back: "Bosh sahifa", project: "Loyiha" },
        process: { title: "Ish Jarayoni", steps: [{ title: "Murojaat", desc: "Telegram yoki Instagram orqali bog'laning" }, { title: "Muhokama", desc: "Loyiha talablari va muddatlarini aniqlaymiz" }, { title: "Ishlab chiqish", desc: "Professional dizayn yaratamiz" }, { title: "Topshirish", desc: "Tayyor fayllarni yuboramiz" }] },
        location: { title: "Manzil", addr: "Vobkent tumani, Buxoro viloyati, O'zbekiston", note: "Online hamkorlik — butun O'zbekiston bo'yicha" },
        contact: { title: "Bog'lanish", sub: "Keling, Loyihangizni Birgalikda Yarataylik", name: "Ismingiz", srv: "Xizmat turi", srvPh: "Xizmatni tanlang", price: "Narxi (taxminan)", tg: "Telegram username (@nickname)", dl: "Muddat (necha kun)", msg: "Xabaringiz (qo'shimcha)", send: "Telegramga Yuborish" },
        pricing: { title: "Narxlar", sub: "Har qanday byudjet uchun qulay narxlar", cur: "so'm", popular: "Mashhur", order: "Zakaz Berish", plans: [{ name: "Boshlang'ich", price: "25 000", desc: "Kichik loyihalar uchun", features: ["1 ta dizayn varianti", "2 ta tuzatish", "PNG/JPG format", "1–2 kun muddat", "Infografika yoki poster"] }, { name: "Standard", price: "50 000", desc: "Ko'pchilik buyurtmachilar tanlovi", features: ["3 ta dizayn varianti", "5 ta tuzatish", "PNG/JPG/PDF format", "2–4 kun muddat", "Har qanday xizmat turi", "Sun'iy intellekt (AI) + Figma)"] }, { name: "Premium", price: "100 000", desc: "Katta va murakkab loyihalar", features: ["Cheksiz variantlar", "Cheksiz tuzatishlar", "Barcha formatlar", "1–3 kun ekspres", "Brend identifikatsiya to'plami", "AI + Figma professional", " Bepul maslahat"] }] }
    },
    ru: {
        nav: { services: "Услуги", portfolio: "Портфолио", process: "Процесс", location: "Локация", contact: "Контакты", order: "Заказать", pricingNav: "Цены", about: "Обо мне", themeDark: "ТЕМНЫЙ", themeLight: "СВЕТЛЫЙ" },
        hero: { badge: "Графический Дизайнер — Вобкент, Бухара", t1: "ГРАФИК", t2: "ДИЗАЙН", t3: "ПОРТФОЛИО", sub: "Инфографика, постеры, брендинг — каждый проект создаётся с уникальным визуальным языком.", btn1: "Посмотреть работы", btn2: "Заказать", s1: "Проектов", s2: "Лет Опыта", s3: "Довольных клиентов" },
        services: { title: "Услуги", sub: "Профессиональные решения для любого проекта", items: [{ title: "Инфографика", desc: "Представление данных в визуальном, лёгком для понимания формате" }, { title: "Дизайн постеров", desc: "Привлекающие внимание постеры для мероприятий, продуктов и кампаний" }, { title: "Фирменный стиль", desc: "Логотип, цвета, шрифты и корпоративный стиль" }, { title: "Социальные сети", desc: "Контент для Instagram, Telegram и других платформ" }, { title: "Презентации", desc: "Профессиональные слайды для бизнеса и образования" }, { title: "Дизайн меню", desc: "Красивые меню для ресторанов" }] },
        portfolio: { title: "Портфолио", sub: "Последние работы", items: ["Дизайн инфографики", "Дизайн постера", "Фирменный стиль", "Контент для соцсетей", "Презентация"], viewAll: "Смотреть все работы" },
        gallery: { title: "Галерея Дизайна", sub: "Коллекция всех проектов", back: "На главную", project: "Проект" },
        process: { title: "Рабочий процесс", steps: [{ title: "Обращение", desc: "Свяжитесь через Telegram или Instagram" }, { title: "Обсуждение", desc: "Уточняем требования и сроки проекта" }, { title: "Разработка", desc: "Создаём профессиональный дизайн" }, { title: "Передача", desc: "Отправляем готовые файлы" }] },
        location: { title: "Местоположение", addr: "Вобкентский район, Бухарская область, Узбекистан", note: "Онлайн сотрудничество — по всему Узбекистану" },
        contact: { title: "Контакты", sub: "Давайте создадим ваш проект вместе", name: "Ваше имя", srv: "Тип услуги", srvPh: "Выберите услугу", price: "Бюджет (примерно)", tg: "Telegram (@ник)", dl: "Срок (сколько дней)", msg: "Сообщение (дополнительно)", send: "Отправить в Telegram" },
        pricing: { title: "Цены", sub: "Доступные цены для любого бюджета", cur: "сум", popular: "Популярный", order: "Заказать", plans: [{ name: "Начальный", price: "25 000", desc: "Для небольших проектов", features: ["1 вариант дизайна", "2 правки", "Формат PNG/JPG", "Срок 1–2 дня", "Инфографика или постер"] }, { name: "Стандарт", price: "50 000", desc: "Выбор большинства заказчиков", features: ["3 варианта дизайна", "5 правок", "Формат PNG/JPG/PDF", "Срок 2–4 дня", "Любой тип услуги", "Искусственный интеллект (AI) + Figma)"] }, { name: "Премиум", price: "100 000", desc: "Для крупных и сложных проектов", features: ["Неограниченные варианты", "Неограниченные правки", "Все форматы", "Экспресс 1–3 дня", "Пакет фирменного стиля", "AI + Figma профессионально", "Kонсультаций"] }] }
    },
    en: {
        nav: { services: "Services", portfolio: "Portfolio", process: "Process", location: "Location", contact: "Contact", order: "Order Now", pricingNav: "Pricing", about: "About Me", themeDark: "DARK", themeLight: "LIGHT" },
        hero: { badge: "Graphic Designer — Vobkent, Bukhara", t1: "GRAPHIC", t2: "DESIGN", t3: "PORTFOLIO", sub: "Infographics, posters, brand identity — every project is crafted with its own unique visual language.", btn1: "View Works", btn2: "Order Now", s1: "Projects", s2: "Years Experience", s3: "Satisfied clients" },
        services: { title: "Services", sub: "Professional solutions for any project", items: [{ title: "Infographics", desc: "Presenting data in a visual, easy-to-understand format" }, { title: "Poster Design", desc: "Eye-catching posters for events, products and campaigns" }, { title: "Brand Identity", desc: "Logo, colors, typography and corporate style" }, { title: "Social Media", desc: "Content for Instagram, Telegram and other platforms" }, { title: "Presentations", desc: "Professional slides for business and education" }, { title: "Menu Design", desc: "Beautiful menus for restaurants" }] },
        portfolio: { title: "Portfolio", sub: "Recent Works", items: ["Infographic Design", "Poster Design", "Brand Identity", "Social Media Content", "Presentation"], viewAll: "View All Works" },
        gallery: { title: "Design Gallery", sub: "Collection of all projects", back: "Back to Home", project: "Project" },
        process: { title: "Work Process", steps: [{ title: "Contact", desc: "Contact via Telegram or Instagram" }, { title: "Discussion", desc: "We discuss project requirements and deadlines" }, { title: "Design", desc: "We create the professional design" }, { title: "Delivery", desc: "We deliver the final files" }] },
        location: { title: "Location", addr: "Vobkent district, Bukhara region, Uzbekistan", note: "Online collaboration — across all of Uzbekistan" },
        contact: { title: "Contact", sub: "Let's create your project together", name: "Your Name", srv: "Service Type", srvPh: "Select a service", price: "Budget (approx.)", tg: "Telegram (@username)", dl: "Deadline (days)", msg: "Message (optional)", send: "Send via Telegram" },
        pricing: { title: "Pricing", sub: "Affordable rates for any budget", cur: "UZS", popular: "Popular", order: "Order Now", plans: [{ name: "Starter", price: "25 000", desc: "For small projects", features: ["1 design variant", "2 revisions", "PNG/JPG format", "1–2 day turnaround", "Infographic or poster"] }, { name: "Standard", price: "50 000", desc: "Most popular choice", features: ["3 design variants", "5 revisions", "PNG/JPG/PDF format", "2–4 day turnaround", "Any service type", "Artificial Intelligence (AI) + Figma"] }, { name: "Premium", price: "100 000", desc: "For large & complex projects", features: ["Unlimited variants", "Unlimited revisions", "All formats", "Express 1–3 days", "Full brand identity kit", "AI + Figma professional", "Free consultation"] }] }
    }
};